version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
  frontend:
    image: nginx:alpine
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "8080:80"
